<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="LibGit2Sharp" Version="0.31.0" />
<!--      <PackageReference Include="Sarsoo.Terraform" Version="0.0.3" />-->
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Sarsoo.Terraform\Sarsoo.Terraform\Sarsoo.Terraform.csproj" />
      <ProjectReference Include="..\Sarsoo.Terraform\TerraformDotnet\src\TerraformDotnet.Hcl\TerraformDotnet.Hcl.csproj" />
      <ProjectReference Include="..\Sarsoo.Terraform\TerraformDotnet\src\TerraformDotnet\TerraformDotnet.csproj" />
    </ItemGroup>

</Project>
