// <auto-generated />
using System;
using System.Text.Json;
using Carnitas.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Carnitas.Model.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260808150425_add_checkout_and_refactor")]
    partial class add_checkout_and_refactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Carnitas.Model.Governance.Organisation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("Carnitas.Model.Governance.Policy.Function", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("Functions");
                });

            modelBuilder.Entity("Carnitas.Model.Governance.Policy.PrincipalResourceFunction", b =>
                {
                    b.Property<string>("PrincipalId")
                        .HasColumnType("text");

                    b.Property<int>("PrincipalType")
                        .HasColumnType("integer");

                    b.Property<string>("ResourceId")
                        .HasColumnType("text");

                    b.Property<int>("ResourceType")
                        .HasColumnType("integer");

                    b.Property<string>("FunctionName")
                        .HasColumnType("text");

                    b.HasKey("PrincipalId", "PrincipalType", "ResourceId", "ResourceType", "FunctionName");

                    b.HasIndex("FunctionName");

                    b.ToTable("PrincipalResourceFunctions");
                });

            modelBuilder.Entity("Carnitas.Model.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Carnitas.Model.Operations.OperationRun", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CheckoutId")
                        .HasColumnType("text");

                    b.Property<string>("CommitSha")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("integer");

                    b.Property<string>("GitReference")
                        .HasColumnType("text");

                    b.Property<string>("LogPath")
                        .HasColumnType("text");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CheckoutId");

                    b.HasIndex("ModuleId");

                    b.ToTable("OperationRuns", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Carnitas.Model.Operations.OperationRunLogEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperationRunId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperationRunId1")
                        .HasColumnType("text");

                    b.Property<JsonElement>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.HasIndex("OperationRunId");

                    b.HasIndex("OperationRunId1");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Type");

                    b.HasIndex("OperationRunId", "Sequence");

                    b.ToTable("OperationRunLogEntries", (string)null);
                });

            modelBuilder.Entity("Carnitas.Model.Source.Module", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("Modules");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Carnitas.Model.Source.SourceControl.Checkout", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<string>("Commit")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.ToTable("Checkouts");
                });

            modelBuilder.Entity("Carnitas.Model.Source.SourceControl.GitHub.GitHubApp", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("InstanceUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrivateKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GitHubApps");
                });

            modelBuilder.Entity("Carnitas.Model.Source.SourceControl.Repository", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("GitHubAppId")
                        .HasColumnType("text");

                    b.Property<string>("GitUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganisationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepositoryUrl")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GitHubAppId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Repository");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Carnitas.Model.Operations.ApplyRun", b =>
                {
                    b.HasBaseType("Carnitas.Model.Operations.OperationRun");

                    b.Property<string>("RepositoryId")
                        .HasColumnType("text");

                    b.HasIndex("RepositoryId");

                    b.ToTable("ApplyRuns", (string)null);
                });

            modelBuilder.Entity("Carnitas.Model.Operations.InitRun", b =>
                {
                    b.HasBaseType("Carnitas.Model.Operations.OperationRun");

                    b.Property<string>("RepositoryId")
                        .HasColumnType("text");

                    b.HasIndex("RepositoryId");

                    b.ToTable("InitRuns", (string)null);
                });

            modelBuilder.Entity("Carnitas.Model.Operations.PlanRun", b =>
                {
                    b.HasBaseType("Carnitas.Model.Operations.OperationRun");

                    b.Property<string>("RepositoryId")
                        .HasColumnType("text");

                    b.HasIndex("RepositoryId");

                    b.ToTable("PlanRuns", (string)null);
                });

            modelBuilder.Entity("Carnitas.Model.Source.RootModule", b =>
                {
                    b.HasBaseType("Carnitas.Model.Source.Module");

                    b.Property<string>("TrackingBranch")
                        .HasColumnType("text");

                    b.ToTable("RootModule", (string)null);
                });

            modelBuilder.Entity("Carnitas.Model.Governance.Policy.PrincipalResourceFunction", b =>
                {
                    b.HasOne("Carnitas.Model.Governance.Policy.Function", "Function")
                        .WithMany("PrincipalResourceFunctions")
                        .HasForeignKey("FunctionName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Function");
                });

            modelBuilder.Entity("Carnitas.Model.Operations.OperationRun", b =>
                {
                    b.HasOne("Carnitas.Model.Source.SourceControl.Checkout", "Checkout")
                        .WithMany()
                        .HasForeignKey("CheckoutId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Carnitas.Model.Source.Module", "Module")
                        .WithMany("OperationRuns")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checkout");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Carnitas.Model.Operations.OperationRunLogEntry", b =>
                {
                    b.HasOne("Carnitas.Model.Operations.OperationRun", "OperationRun")
                        .WithMany()
                        .HasForeignKey("OperationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carnitas.Model.Operations.OperationRun", null)
                        .WithMany("LogEntries")
                        .HasForeignKey("OperationRunId1");

                    b.Navigation("OperationRun");
                });

            modelBuilder.Entity("Carnitas.Model.Source.Module", b =>
                {
                    b.HasOne("Carnitas.Model.Source.SourceControl.Repository", "Repository")
                        .WithMany("Modules")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Carnitas.Model.Source.SourceControl.Checkout", b =>
                {
                    b.HasOne("Carnitas.Model.Source.SourceControl.Repository", "Repository")
                        .WithMany("Checkouts")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Carnitas.Model.Source.SourceControl.Repository", b =>
                {
                    b.HasOne("Carnitas.Model.Source.SourceControl.GitHub.GitHubApp", "GitHubApp")
                        .WithMany()
                        .HasForeignKey("GitHubAppId");

                    b.HasOne("Carnitas.Model.Governance.Organisation", "Organisation")
                        .WithMany("Repositories")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GitHubApp");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Carnitas.Model.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Carnitas.Model.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carnitas.Model.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Carnitas.Model.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnitas.Model.Operations.ApplyRun", b =>
                {
                    b.HasOne("Carnitas.Model.Operations.OperationRun", null)
                        .WithOne()
                        .HasForeignKey("Carnitas.Model.Operations.ApplyRun", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carnitas.Model.Source.SourceControl.Repository", null)
                        .WithMany("ApplyRuns")
                        .HasForeignKey("RepositoryId");
                });

            modelBuilder.Entity("Carnitas.Model.Operations.InitRun", b =>
                {
                    b.HasOne("Carnitas.Model.Operations.OperationRun", null)
                        .WithOne()
                        .HasForeignKey("Carnitas.Model.Operations.InitRun", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carnitas.Model.Source.SourceControl.Repository", null)
                        .WithMany("InitRuns")
                        .HasForeignKey("RepositoryId");
                });

            modelBuilder.Entity("Carnitas.Model.Operations.PlanRun", b =>
                {
                    b.HasOne("Carnitas.Model.Operations.OperationRun", null)
                        .WithOne()
                        .HasForeignKey("Carnitas.Model.Operations.PlanRun", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carnitas.Model.Source.SourceControl.Repository", null)
                        .WithMany("PlanRuns")
                        .HasForeignKey("RepositoryId");
                });

            modelBuilder.Entity("Carnitas.Model.Source.RootModule", b =>
                {
                    b.HasOne("Carnitas.Model.Source.Module", null)
                        .WithOne()
                        .HasForeignKey("Carnitas.Model.Source.RootModule", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnitas.Model.Governance.Organisation", b =>
                {
                    b.Navigation("Repositories");
                });

            modelBuilder.Entity("Carnitas.Model.Governance.Policy.Function", b =>
                {
                    b.Navigation("PrincipalResourceFunctions");
                });

            modelBuilder.Entity("Carnitas.Model.Operations.OperationRun", b =>
                {
                    b.Navigation("LogEntries");
                });

            modelBuilder.Entity("Carnitas.Model.Source.Module", b =>
                {
                    b.Navigation("OperationRuns");
                });

            modelBuilder.Entity("Carnitas.Model.Source.SourceControl.Repository", b =>
                {
                    b.Navigation("ApplyRuns");

                    b.Navigation("Checkouts");

                    b.Navigation("InitRuns");

                    b.Navigation("Modules");

                    b.Navigation("PlanRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
