syntax = "proto3";

option csharp_namespace = "Carnitas.Grpc";

package agent;

service Agent {
  rpc ReportOperationLogs(stream OperationLog) returns (OperationLogResponse);
  rpc ReportOperationStatus(OperationStatusRequest) returns (OperationStatusResponse);
  rpc SubmitOperationPlan(OperationPlanReport) returns (OperationPlanResponse);
  
  rpc RequestWorkflow(OperationRequest) returns (WorkflowRequestResponse);
}

/////////////////////////
// ReportOperationLogs
////////////////////////

message OperationLog {
  string operation_id = 1;
  string log = 2;
}

message OperationLogResponse {
  
}

////////////////////////////////
//   ReportOperationStatus
///////////////////////////////

enum OperationStatusState {
  OPERATION_SUCCESS = 0;
  OPERATION_FAILURE = 1;
  OPERATION_UNKNOWN = 2;
}

message OperationStatusRequest {
  string operation_id = 1;
  OperationStatusState state = 2;
}

message OperationStatusResponse {
  string operation_id = 1;
}

////////////////////////////////
//   ReportOperationStatus
///////////////////////////////

message OperationPlanReport {
  string operation_id = 1;
  string plan = 2;
  string plan_file_path = 3;
}

message OperationPlanResponse {

}

////////////////////////////////
//     RequestWorkflow
///////////////////////////////

message OperationRequest {
  string worker_id = 1;
}

message WorkflowRequestResponse {
  string id = 1;
  string repo_url = 2;
  string module_path = 3;
  repeated OperationResponse operations = 4;
}

message OperationResponse {
  string id = 1;
  OperationType operation = 2;
}

enum OperationType {
  OPERATION_INIT = 0;
  OPERATION_PLAN = 1;
  OPERATION_APPLY = 2;
}