<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>cns</AssemblyName>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <PropertyGroup>
        <PublishAot>true</PublishAot>
        <PublishSelfContained>true</PublishSelfContained>
        <!--    <IsTrimmable>true</IsTrimmable>-->
        <EnableAotAnalyzer>true</EnableAotAnalyzer>
        <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
        <OptimizationPreference>Speed</OptimizationPreference>
        <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Carnitas\Carnitas.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="LibGit2Sharp" Version="0.31.0" />
<!--      <PackageReference Include="Sarsoo.Terraform" Version="0.0.3" />-->
      <PackageReference Include="System.CommandLine" Version="2.0.7" />
    </ItemGroup>

</Project>
