<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.1" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Carnitas.CLI\Carnitas.CLI.csproj" />
      <ProjectReference Include="..\Carnitas.Grpc\Carnitas.Grpc.csproj" />
      <ProjectReference Include="..\Carnitas.Model\Carnitas.Model.csproj" />
      <ProjectReference Include="..\Carnitas.Web\Carnitas.Web.csproj" />
      <ProjectReference Include="..\Carnitas\Carnitas.csproj" />
    </ItemGroup>

</Project>